### ISSUE TITLE
Create prototype implementation outline

### ISSUE THREAD

**Issue by rpappalax** [mozilla-services/deployment-pipeline#3]
@oremj created the prototype abstract outline

We should start tolist potential technologies for implementation (pro/cons, etc.)
what will be the main pipeline? (jenkins, codedeploy, cloudformation, etc.)
what will be the ancillary technologies (puppet, ansible, vagrant?)

**Comment by oremj** [comment]
For the initial prototype we will be using jenkins and the existing deployment tools (cloudformation, ansible, puppet, etc)
